# Generated by Django 3.1.2 on 2020-11-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
